// Generated by gencpp from file robot_pkg/robotJointAction.msg
// DO NOT EDIT!


#ifndef ROBOT_PKG_MESSAGE_ROBOTJOINTACTION_H
#define ROBOT_PKG_MESSAGE_ROBOTJOINTACTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace robot_pkg
{
template <class ContainerAllocator>
struct robotJointAction_
{
  typedef robotJointAction_<ContainerAllocator> Type;

  robotJointAction_()
    : header()
    , motor(0)
    , action(0)
    , position(0)
    , velocity(0)  {
    }
  robotJointAction_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , motor(0)
    , action(0)
    , position(0)
    , velocity(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int8_t _motor_type;
  _motor_type motor;

   typedef int8_t _action_type;
  _action_type action;

   typedef int16_t _position_type;
  _position_type position;

   typedef int16_t _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::robot_pkg::robotJointAction_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_pkg::robotJointAction_<ContainerAllocator> const> ConstPtr;

}; // struct robotJointAction_

typedef ::robot_pkg::robotJointAction_<std::allocator<void> > robotJointAction;

typedef boost::shared_ptr< ::robot_pkg::robotJointAction > robotJointActionPtr;
typedef boost::shared_ptr< ::robot_pkg::robotJointAction const> robotJointActionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_pkg::robotJointAction_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_pkg::robotJointAction_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_pkg

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'robot_pkg': ['/home/salaceri/robotica_ws/src/robot/robot_pkg/msg', '/home/salaceri/robotica_ws/src/robot/robot_pkg/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_pkg::robotJointAction_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_pkg::robotJointAction_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_pkg::robotJointAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_pkg::robotJointAction_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_pkg::robotJointAction_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_pkg::robotJointAction_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_pkg::robotJointAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d0326b0598c600658f7dc5ddec01e4b4";
  }

  static const char* value(const ::robot_pkg::robotJointAction_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd0326b0598c60065ULL;
  static const uint64_t static_value2 = 0x8f7dc5ddec01e4b4ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_pkg::robotJointAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_pkg/robotJointAction";
  }

  static const char* value(const ::robot_pkg::robotJointAction_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_pkg::robotJointAction_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
Header           header\n\
int8           motor\n\
int8           action\n\
int16           position\n\
int16           velocity\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::robot_pkg::robotJointAction_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_pkg::robotJointAction_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.motor);
      stream.next(m.action);
      stream.next(m.position);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robotJointAction_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_pkg::robotJointAction_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_pkg::robotJointAction_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "motor: ";
    Printer<int8_t>::stream(s, indent + "  ", v.motor);
    s << indent << "action: ";
    Printer<int8_t>::stream(s, indent + "  ", v.action);
    s << indent << "position: ";
    Printer<int16_t>::stream(s, indent + "  ", v.position);
    s << indent << "velocity: ";
    Printer<int16_t>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_PKG_MESSAGE_ROBOTJOINTACTION_H
